services:
  utorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: utorrent
    networks:
      - proxy
    hostname: utorrent
    dns: 
      - 172.22.20.1
      - 8.8.8.8
    volumes:
      - ./config:/config
      - /downloads:/downloads
      - /downloads:/download
    environment:
      - APP_GROUP=Content
      - APP_LOGO=https://iconape.com/wp-content/files/zo/346429/png/346429.png
      - VIRTUAL_HOST=ut.admin.pknw1.co.uk,utorrent.admin.pknw1.co.uk
      - VIRTUAL_PORT=8080


networks:
  proxy:
    external: true

