services:
  utorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: utorrent
    networks:
      - proxy
    hostname: utorrent
    dns: 
      - 172.22.20.1
      - 8.8.8.8
    volumes:
      - ./config:/config
      - /downloads:/downloads
      - /downloads:/download
    environment:
      - APP_GROUP=Content
      - APP_LOGO=https://iconape.com/wp-content/files/zo/346429/png/346429.png
      - VIRTUAL_HOST=ut.admin.pknw1.co.uk,utorrent.admin.pknw1.co.uk
      - VIRTUAL_PORT=8080

  flaresolverr: 
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - proxy
    hostname: flaresolverr
    dns: 
      - 172.22.20.1
      - 8.8.8.8
    environment:
      - LOG_LEVEL=info
      - APP_GROUP=Content
      - APP_LOGO=https://avatars.githubusercontent.com/u/75936191?s=400&v=4
      - VIRTUAL_HOST=flaresolverr.admin.pknw1.co.uk
      - VIRTUAL_PORT=8191
    ports:
      - 172.22.20.1:8191:8191
  

networks:
  proxy:
    external: true

